[package]
name = "tokio-openssl"
version = "0.6.0"
authors = ["Alex Crichton <alex@alexcrichton.com>"]
license = "MIT/Apache-2.0"
edition = "2018"
repository = "https://github.com/alexcrichton/tokio-openssl"
homepage = "https://github.com/alexcrichton/tokio-openssl"
documentation = "https://docs.rs/tokio-openssl"
description = """
An implementation of SSL streams for Tokio backed by OpenSSL
"""

[dependencies]
openssl = "0.10.30"
openssl-sys = "0.9.58"
tokio = "1.0"

[dev-dependencies]
futures = "0.3"
tokio = { version = "1.0", features = ["full"] }
