[package]
name = "tokio-openssl"
version = "0.1.4"
authors = ["Alex Crichton <alex@alexcrichton.com>"]
license = "MIT/Apache-2.0"
repository = "https://github.com/alexcrichton/tokio-openssl"
homepage = "https://github.com/alexcrichton/tokio-openssl"
documentation = "https://docs.rs/tokio-openssl"
description = """
An implementation of SSL streams for Tokio backed by OpenSSL
"""
publish = false # needs a major version bump w/ new openssl version

[dependencies]
openssl = "0.10.1"
futures = "0.1.11"
tokio-core = "0.1.6"
tokio-io = "0.1"
