[package]
name = "tokio-openssl"
version = "0.4.0-alpha.5"
authors = ["Alex Crichton <alex@alexcrichton.com>"]
license = "MIT/Apache-2.0"
edition = "2018"
repository = "https://github.com/alexcrichton/tokio-openssl"
homepage = "https://github.com/alexcrichton/tokio-openssl"
documentation = "https://docs.rs/tokio-openssl"
description = """
An implementation of SSL streams for Tokio backed by OpenSSL
"""

[dependencies]
openssl = "0.10.1"
tokio-io = "=0.2.0-alpha.6"

[dev-dependencies]
futures-preview = "=0.3.0-alpha.19"
tokio = "=0.2.0-alpha.6"
