[package]
name = "tokio-openssl"
version = "0.5.0"
authors = ["Alex Crichton <alex@alexcrichton.com>"]
license = "MIT/Apache-2.0"
edition = "2018"
repository = "https://github.com/alexcrichton/tokio-openssl"
homepage = "https://github.com/alexcrichton/tokio-openssl"
documentation = "https://docs.rs/tokio-openssl"
description = """
An implementation of SSL streams for Tokio backed by OpenSSL
"""

[dependencies]
futures = "0.3"
openssl = "0.10.30"
pin-project = "1.0"
tokio = "1.0"

[dev-dependencies]
tokio = { version = "1.0", features = ["full"] }

[patch.crates-io]
openssl = { git = "https://github.com/sfackler/rust-openssl", branch = "always-unpin" }
